version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: 4linux_test
      POSTGRES_PASSWORD: usuarioroot
      POSTGRES_DB: 4LinuxUI
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
